language: r
dist: bionic
cache: packages

r_github_packages:
  - richelbilderbeek/beautier@develop
  - richelbilderbeek/beastier
  - richelbilderbeek/babette

before_script:
  - Rscript -e "beastier::install_beast2()"

script:
  - Rscript reprex.R

